# Generated by Django 5.0.6 on 2026-05-30

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ejemplo: Norte Integrado, Valles Cruceños, Chiquitania', max_length=100, unique=True, verbose_name='Nombre de la Región')),
                ('description', models.TextField(blank=True, help_text='Detalles sobre el relieve, clima predominante, principales cultivos u observaciones.', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClimatePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(help_text='Fecha en la que el modelo de IA ejecutó y guardó la predicción.', verbose_name='Fecha de Predicción')),
                ('target_date', models.DateField(help_text='Fecha futura (habitualmente 12 meses adelante) para la cual se predice el clima.', verbose_name='Fecha Objetivo')),
                ('anomaly_type', models.CharField(choices=[('SEQUIA', 'Sequía'), ('INUNDACION', 'Inundación'), ('NORMAL', 'Normal (Sin Anomalías)')], default='NORMAL', max_length=20, verbose_name='Tipo de Anomalía Climática')),
                ('severity_level', models.IntegerField(help_text='Escala del 1 al 5 (1: Muy Leve, 2: Leve, 3: Moderado, 4: Severo, 5: Extremo/Catastrófico)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nivel de Severidad (1-5)')),
                ('confidence_score', models.FloatField(help_text='Nivel de probabilidad o certeza calculado por Vertex AI (ej. 0.85)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Índice de Confianza (0.0 - 1.0)')),
                ('vertex_ai_output', models.JSONField(blank=True, help_text='Payload crudo JSON devuelto por Google Vertex AI. Contiene métricas de importancia, versión del modelo, etc.', null=True, verbose_name='Output Detallado de Vertex AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='climate_intelligence.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Predicción Climática',
                'verbose_name_plural': 'Predicciones Climáticas',
                'ordering': ['-target_date', 'region'],
                'unique_together': {('region', 'target_date', 'prediction_date')},
            },
        ),
    ]
