# Generated by Django 5.0.14 on 2026-05-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='area_hectares',
            field=models.IntegerField(blank=True, help_text='Superficie estimada productiva en hectáreas', null=True, verbose_name='Superficie (ha)'),
        ),
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Coordenada de latitud del epicentro de la región (ej. -17.33)', null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Coordenada de longitud del epicentro de la región (ej. -63.25)', null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='region',
            name='main_crops',
            field=models.CharField(blank=True, help_text='Ej: Soya, Caña de Azúcar, Arroz', max_length=255, verbose_name='Cultivos Principales'),
        ),
    ]
