# Generated by Django 5.0.14 on 2026-05-30 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_intelligence', '0002_region_area_hectares_region_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitud del centroide de la región (ej. -16.5)', null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitud del centroide de la región (ej. -63.2)', null=True, verbose_name='Longitud'),
        ),
        migrations.CreateModel(
            name='ClimateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('EXTREME', 'Extremo')], max_length=10, verbose_name='Nivel de Alerta')),
                ('title', models.CharField(help_text='Título corto y claro para notificaciones push (máx 120 chars)', max_length=120, verbose_name='Título de la Alerta')),
                ('message_short', models.TextField(help_text='Mensaje para SMS/WhatsApp en lenguaje simple para el agricultor (máx 160 chars)', verbose_name='Mensaje Corto (SMS/WhatsApp)')),
                ('message_long', models.TextField(help_text='Explicación detallada de la alerta en 2-3 párrafos generada por Gemini', verbose_name='Mensaje Completo')),
                ('agronomic_tips', models.JSONField(default=list, help_text='Lista de 3-5 acciones concretas que el agricultor debe tomar', verbose_name='Recomendaciones Agronómicas')),
                ('generated_by', models.CharField(default='template_fallback', help_text="Modelo LLM utilizado (ej. 'gemini-1.5-flash') o 'template_fallback'", max_length=60, verbose_name='Generado por')),
                ('is_sent', models.BooleanField(default=False, help_text='Indica si la alerta fue enviada a los productores de la región', verbose_name='¿Enviada?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Generada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='climate_intelligence.climateprediction', verbose_name='Predicción Asociada')),
            ],
            options={
                'verbose_name': 'Alerta Climática',
                'verbose_name_plural': 'Alertas Climáticas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClimateDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(choices=[('OPEN_METEO', 'Open-Meteo (Archivo Histórico)'), ('NASA_POWER', 'NASA POWER API'), ('CHIRPS', 'CHIRPS (Precipitación Satelital)'), ('MOCK', 'Datos Simulados (Desarrollo)')], default='MOCK', max_length=20, verbose_name='Fuente de Datos')),
                ('variable_name', models.CharField(help_text='Ej: precipitation_sum, temperature_2m_max, soil_moisture_0_7cm', max_length=60, verbose_name='Variable Climática')),
                ('date', models.DateField(verbose_name='Fecha de Observación')),
                ('value', models.FloatField(help_text='Valor numérico de la variable en la unidad correspondiente', verbose_name='Valor')),
                ('unit', models.CharField(help_text='Ej: mm, °C, m³/m³, %', max_length=30, verbose_name='Unidad')),
                ('raw_response', models.JSONField(blank=True, help_text='Payload JSON completo de la respuesta de la API externa para auditoría', null=True, verbose_name='Respuesta Cruda de la API')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Obtenido el')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_data', to='climate_intelligence.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Dato Climático',
                'verbose_name_plural': 'Datos Climáticos',
                'ordering': ['-date', 'region', 'variable_name'],
                'indexes': [models.Index(fields=['region', 'variable_name', 'date'], name='climate_int_region__9e0f8b_idx')],
                'unique_together': {('region', 'source_name', 'variable_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SatelliteObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_date', models.DateField(help_text='Fecha de la captura satelital', verbose_name='Fecha de Observación')),
                ('ndvi', models.FloatField(help_text='Índice de Vegetación de Diferencia Normalizada (-1 a 1). >0.5 = vegetación densa/sana', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='NDVI')),
                ('ndwi', models.FloatField(help_text='Índice de Agua de Diferencia Normalizada (-1 a 1). >0 = presencia de agua en superficie', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='NDWI')),
                ('cloud_cover_pct', models.FloatField(blank=True, help_text='Porcentaje de nubosidad en la imagen (afecta calidad del dato)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Cobertura de Nubes (%)')),
                ('source', models.CharField(choices=[('MODIS', 'MODIS (Terra/Aqua)'), ('SENTINEL_2', 'Sentinel-2 (ESA Copernicus)'), ('LANDSAT', 'Landsat-8/9 (USGS)'), ('MOCK', 'Datos Simulados (Desarrollo)')], default='MOCK', max_length=15, verbose_name='Fuente Satelital')),
                ('raw_data', models.JSONField(blank=True, help_text='Metadatos completos de la imagen satelital', null=True, verbose_name='Datos Crudos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_observations', to='climate_intelligence.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Observación Satelital',
                'verbose_name_plural': 'Observaciones Satelitales',
                'ordering': ['-obs_date', 'region'],
                'indexes': [models.Index(fields=['region', 'obs_date'], name='climate_int_region__6ef1f9_idx')],
                'unique_together': {('region', 'obs_date', 'source')},
            },
        ),
    ]
