"""
Django settings for AgriTech climate intelligence platform.

Generated by Antigravity AI assistant.
"""

import os
from pathlib import Path
import environ

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False),
    SECRET_KEY=(str, 'django-insecure-default-change-this-in-production-12345'),
    DATABASE_URL=(str, 'postgres://postgres:postgres@db:5432/agritech'),
    ALLOWED_HOSTS=(list, ['*']),
    CORS_ALLOW_ALL_ORIGINS=(bool, False),
    CORS_ALLOWED_ORIGINS=(list, []),
    CSRF_TRUSTED_ORIGINS=(list, []),
    # Google Gemini LLM para alertas en lenguaje natural
    GEMINI_API_KEY=(str, ''),
    GEMINI_MODEL=(str, 'gemini-1.5-flash'),
    # APIs climáticas externas
    OPEN_METEO_BASE_URL=(str, 'https://archive-api.open-meteo.com/v1/archive'),
    NASA_POWER_BASE_URL=(str, 'https://power.larc.nasa.gov/api/temporal/daily/point'),
    # Modos de operación
    USE_REAL_CLIMATE_DATA=(bool, False),
    USE_GEMINI_ALERTS=(bool, True),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file from the base directory if it exists (useful for local docker-compose/development)
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(str(env_file))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    # Core Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # WhiteNoise is placed here to support static files serving under runserver in non-debug mode
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',

    # Third-party applications
    'corsheaders',

    # AgriTech platform applications
    'climate_intelligence.apps.ClimateIntelligenceConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise must be placed directly under SecurityMiddleware for optimal caching and serving
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CORS middleware needs to be placed before CommonMiddleware to intercept requests properly
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database Configuration
# Parses the DATABASE_URL environment variable (supports postgresql, mysql, sqlite, etc.)
DATABASES = {
    'default': env.db('DATABASE_URL')
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization (Optimized for Santa Cruz, Bolivia)
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-bo'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# Configured for WhiteNoise optimization on Google Cloud Run
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise storage engine for manifest caching and compression (gzip/brotli)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS Configuration
# Used by django-cors-headers to manage origins that can request data from the API
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=False)
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# If DEBUG is True, print SQL logs or add other dev helpers if needed
if DEBUG:
    # Optional debug-only settings can be configured here
    pass


# ==============================================================================
# Configuración del Sistema de Inteligencia Climática
# ==============================================================================

# Google Gemini — LLM para generar alertas agronómicas en lenguaje natural
GEMINI_API_KEY = env('GEMINI_API_KEY')
GEMINI_MODEL = env('GEMINI_MODEL')

# APIs de datos climáticos externos
OPEN_METEO_BASE_URL = env('OPEN_METEO_BASE_URL')
NASA_POWER_BASE_URL = env('NASA_POWER_BASE_URL')

# Flags de modo de operación
# False = usar datos mock realistas (desarrollo local sin internet requerido)
# True  = conectar a APIs externas reales (producción / integración)
USE_REAL_CLIMATE_DATA = env.bool('USE_REAL_CLIMATE_DATA', default=False)
USE_GEMINI_ALERTS = env.bool('USE_GEMINI_ALERTS', default=True)

# Production and Development Console Logging for GCP Cloud Run
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

